AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-weather-system

  サーバーレス会員制天気ニュースシステム

Globals:
  Function:
    Timeout: 30
    Runtime: python3.12
    Environment:
      Variables:
        WEATHER_TABLE: !Ref WeatherTable
        TABLE_NAME: !Ref WeatherTable
        COGNITO_USER_POOL_ID: !Ref CognitoUserPool
        COGNITO_CLIENT_ID: !Ref CognitoUserPoolClient

Parameters:
  Stage:
    Type: String
    Default: dev
    Description: Deployment stage

Resources:
  # DynamoDB Table for Weather Data
  WeatherTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-weather-data"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: CityId
          AttributeType: N
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: CityId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: timestamp-index
          KeySchema:
            - AttributeName: timestamp
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  # Cognito User Pool
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${AWS::StackName}-user-pool"
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true

  # Cognito User Pool Client
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "${AWS::StackName}-client"
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH

  # API Gateway
  WeatherApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${AWS::StackName}-api"
      StageName: !Ref Stage
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt CognitoUserPool.Arn

  # Weather Lambda Function
  WeatherFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-weather-handler"
      CodeUri: src/
      Handler: weather_handler.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref WeatherTable
      Events:
        GetHealth:
          Type: Api
          Properties:
            RestApiId: !Ref WeatherApi
            Path: /health
            Method: GET
            Auth:
              Authorizer: NONE
        GetWeather:
          Type: Api
          Properties:
            RestApiId: !Ref WeatherApi
            Path: /weather
            Method: GET
        GenerateWeather:
          Type: Api
          Properties:
            RestApiId: !Ref WeatherApi
            Path: /weather/generate
            Method: POST
        GetForecast:
          Type: Api
          Properties:
            RestApiId: !Ref WeatherApi
            Path: /weather/forecast
            Method: GET
        GetStatistics:
          Type: Api
          Properties:
            RestApiId: !Ref WeatherApi
            Path: /weather/statistics
            Method: GET
        GetWeatherTypes:
          Type: Api
          Properties:
            RestApiId: !Ref WeatherApi
            Path: /weather/types
            Method: GET
            Auth:
              Authorizer: NONE

  # CSV Ingest S3 Bucket
  CsvIngestBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-csv-ingest-${AWS::AccountId}"

  # CSV Ingest Lambda Function
  CsvIngestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-csv-ingest"
      CodeUri: csv_ingest/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref WeatherTable
        - S3ReadPolicy:
            BucketName: !Sub "${AWS::StackName}-csv-ingest-${AWS::AccountId}"
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref CsvIngestBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .csv

  # S3 Bucket for Frontend
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-frontend-${AWS::AccountId}"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  # S3 Bucket Policy for Frontend
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${FrontendBucket.Arn}/*"

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ""
          - Id: ApiOrigin
            DomainName: !Sub "${WeatherApi}.execute-api.${AWS::Region}.amazonaws.com"
            CustomOriginConfig:
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
        CacheBehaviors:
          - PathPattern: "/api/*"
            TargetOriginId: ApiOrigin
            ViewerProtocolPolicy: https-only
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - POST
              - PATCH
              - DELETE
            ForwardedValues:
              QueryString: true
              Headers:
                - Authorization
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${WeatherApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"

  CognitoUserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref CognitoUserPool

  CognitoClientId:
    Description: Cognito Client ID
    Value: !Ref CognitoUserPoolClient

  FrontendBucketName:
    Description: Frontend S3 Bucket Name
    Value: !Ref FrontendBucket

  CloudFrontDomain:
    Description: CloudFront Distribution Domain
    Value: !GetAtt CloudFrontDistribution.DomainName

  CsvIngestBucketName:
    Description: CSV Ingest S3 Bucket Name
    Value: !Ref CsvIngestBucket

  WeatherTableName:
    Description: DynamoDB Table Name
    Value: !Ref WeatherTable
